server:
  port: 8081
spring:
  application:
    name: hangout
  mvc:
    static-path-pattern: /resources/**
    
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
